DEFAULTS: &DEFAULTS
 application_name: crc_estimator
 protocol: http

development:
 <<: *DEFAULTS
 api_server: api-stage.carboncalculated.com
 api_key: 

test:
 <<: *DEFAULTS
 host: localhost.com
 protocol: "http"
 api_server: api-stage.carboncalculated.com
 api_key: 

production:
 <<: *DEFAULTS
 api_server: api.carboncalculated.com
 api_key: 

staging:
 <<: *DEFAULTS
 api_server: api-stage.carboncalculated.com
 api_key: 
 
